import './globals.scss'
import { Inter } from 'next/font/google'
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
    return (
        <html lang='pt-BR' className={inter.className}>
            <body className='body'>{children}</body>
        </html>
    )
}
